# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ReshapeM_rcpp <- function(fnameM, fnameMt, indxNA, dims) {
    .Call('_Eagle_ReshapeM_rcpp', fnameM, fnameMt, indxNA, dims)
}

getRowColumn <- function(fname) {
    .Call('_Eagle_getRowColumn', fname)
}

createMt_ASCII_rcpp <- function(f_name, f_name_ascii, type, max_memory_in_Gbytes, dims, quiet, message) {
    invisible(.Call('_Eagle_createMt_ASCII_rcpp', f_name, f_name_ascii, type, max_memory_in_Gbytes, dims, quiet, message))
}

calculate_reduced_a_rcpp <- function(f_name_ascii, varG, P, y, max_memory_in_Gbytes, dims, selected_loci, quiet, message) {
    .Call('_Eagle_calculate_reduced_a_rcpp', f_name_ascii, varG, P, y, max_memory_in_Gbytes, dims, selected_loci, quiet, message)
}

calculate_a_and_vara_rcpp <- function(f_name_ascii, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message) {
    .Call('_Eagle_calculate_a_and_vara_rcpp', f_name_ascii, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message)
}

createM_ASCII_rcpp <- function(f_name, f_name_ascii, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing) {
    .Call('_Eagle_createM_ASCII_rcpp', f_name, f_name_ascii, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing)
}

extract_geno_rcpp <- function(f_name_ascii, max_memory_in_Gbytes, selected_locus, dims) {
    .Call('_Eagle_extract_geno_rcpp', f_name_ascii, max_memory_in_Gbytes, selected_locus, dims)
}

calculateMMt_rcpp <- function(f_name_ascii, max_memory_in_Gbytes, num_cores, selected_loci, dims, quiet, message) {
    .Call('_Eagle_calculateMMt_rcpp', f_name_ascii, max_memory_in_Gbytes, num_cores, selected_loci, dims, quiet, message)
}

